# Config file for automatic testing at travis-ci.org
sudo: false
language: python
python:
  - 3.7
  - 3.6
  - 3.5

env:
  global:
  - secure: "nPG6veYLoq/o6Hg6h/O6+ZkZgFVKyMch16+KIUSfHI0RK+2LD3BM0HsMmhuMbkwOjiLCSSU6N260eReIYZpcvoBHzxA32VeX3VeKp572LOKWN1FG1+/R7ebzbEXkLWQHAMavFr+5IJfGMOZB/y9jbMSBLKVLRC51EJFnt8lg4/2Wlcy7/i02nSvjD0ToIKk33gOCXKjk6TH1BsuuvrnjSEmvEQscrqN7kVjhB/QEGBXqi6vn0YcS2FO+EcAXtJ5zoEi4eRi6DOAl0RndfHSTmzc6Row5nvWRT/OJdEroA1q5xfjArskpQBe3kLZ/XpFPTMHznBbtTIddZlS0GdtisfU+z/d4Ez2HezDsDkHRiGdE90M4f7TnAcNuxOGXaBxaNooMD7oLerPvV0YzoyQqrY/sR/nPGhk3psxzczWiUMZGQfDOLID/IFG9wH+yOo68VYrLQwNBZMPqWK+EIDGTejx5jAtODN8Jy7h4bQC/vjfNOr7t7ne2sJMYsGwZNnpp7zFYw1EsqBLgz55/aOfcIem/7BvYT4bghRg6JfVfk+drDkiEPUTPtJ5Y9xbsqEJuzM0NPNv6tM/aw0dEYVPwsPc3jcnKG6T+ZG4/AGM+KiYWnDwRZ7pNYva730su3mtTDGcGnWYv6+y/bteGOfDmXfUHQC0GRCYHQMrG8emdTjM="

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U poetry
- pip install -U tox-travis 


# Command to run tests, e.g. python setup.py test
script: tox

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password

before-deploy:
- poetry config http-basic.mypypi wboxx1 $TRAVIS_PASS
- poetry build

deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
    repo: wboxx1/obscura-tools
    branch: master
    python: 3.6
